// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfafaqldcydhonaqaaon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYWZhcWxkY3lkaG9uYXFhYW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjAzNTMsImV4cCI6MjA2NTgzNjM1M30.GXJ8gJUgmRMLGk061pLUYOdt6XUV5Kc6eMZOXn2yxx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);